prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: ingress
        static_configs:
          - targets:
              - ingress-ingress-nginx-controller-metrics:10254

#     - job_name: frontend
#       static_configs:
#         - targets:
#             - frontend:9113

